version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  apt_packages:
    - graphviz
    - libgraphviz-dev

sphinx:
  configuration: docs/conf.py

formats: all

python:
  install:
    - method: pip
      path: .
