name: pyemap
channels:
   - conda-forge
dependencies:
   - rdkit
   - pygraphviz
   - pip:
      - cariosvg
      - gspan_mining
      - sphinxcontrib-pseudocode
      - pysmiles
   - numpy
   - scipy
   - biopython
   - pillow
   - networkx 
   - requests

