name: pyemap
channels:
   - conda-forge
dependencies:
   - rdkit
   - pygraphviz
   - numpy
   - scipy
   - biopython
   - pillow
   - networkx 
   - pysmiles
   - requests
   - cariosvg
   - gspan_mining
